name:                advent-of-code2024
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- unordered-containers
- hashable
- vector
- split
- safe
- either
- megaparsec
- optparse-applicative
- witherable
- neat-interpolation
- recursion-schemes
- data-fix
- pretty
- comonad
- adjunctions
- logict
- machines

default-extensions:
- OverloadedStrings

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wunused-packages

library:
  source-dirs: src

executables:
  aoc2024:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - advent-of-code2024

tests:
  aoc2024-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code2024
    - hspec
    - hspec-discover
    - QuickCheck

benchmarks:
  aoc2024-benchmarks:
    main: Main.hs
    source-dirs: benchmarks
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-s
    dependencies:
      - advent-of-code2024
      - base
      - criterion

verbatim:
  cabal-version: 3.0
